# -*- mode: ruby -*-
# vi: set ft=ruby :

# Our provisioning script
$provision = <<PROVISION
echo Provisioning Cyphre Client Win32 X-Compile VM

# Add MinGW repos
zypper -n ar -G http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/windows:mingw:win32.repo
zypper -n ar -G http://download.opensuse.org/repositories/windows:/mingw/openSUSE_13.2/windows:mingw.repo

# Make sure the entire system is up-to-date
zypper -n update

# Install needed MinGW packages
zypper -n install cmake mingw32-cross-binutils mingw32-cross-cpp \
	mingw32-cross-gcc mingw32-cross-gcc-c++ mingw32-cross-pkg-config \
	mingw32-filesystem mingw32-headers mingw32-runtime \
	mingw32-sqlite-devel mingw32-cross-libqt5-qmake \
	mingw32-libssh2-devel kdewin-png2ico mingw32-libqt5-qtbase-devel \
	mingw32-libgcrypt-devel mingw32-libgnutls-devel \
	mingw32-libneon-openssl mingw32-libbeecrypt-devel mingw32-openssl \
	mingw32-libpng-devel mingw32-qt5keychain-devel mingw32-libintl-devel \
	mingw32-libneon-devel mingw32-libopenssl-devel mingw32-libproxy-devel \
	mingw32-libxml2-devel mingw32-zlib-devel mingw32-cross-nsis \
	mingw32-libqt5-qtwebkit-devel mingw32-libqt5-qtwebkit \
	mingw32-libqt5-qtquick1-devel mingw32-libqt5-qtquick1 \
	mingw32-libqt5-qtdeclarative-devel mingw32-cross-libqt5-qttools \
	mingw32-libqt5-qttools mingw32-angleproject-devel \
	mingw32-libqt5-qttranslations mingw32-qt5keychain

# Plugins for our installer
rpm -ivh http://download.tomahawk-player.org/packman/mingw:32/openSUSE_12.1/x86_64/mingw32-cross-nsis-plugin-processes-0-1.1.x86_64.rpm
rpm -ivh http://download.tomahawk-player.org/packman/mingw:32/openSUSE_12.1/x86_64/mingw32-cross-nsis-plugin-uac-0-3.1.x86_64.rpm

PROVISION

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box = "webhippie/opensuse-13.2"

	# Change this if you want a different port to the web server
	config.vm.network :forwarded_port, guest: 80, host: 8080

	config.vm.provider :virtualbox do |v|
		# allocate 2 CPU Cores
		v.cpus = 2
		# allocate 1024 mb RAM
		v.memory = 1024
	end

	# Setup the needed configurations
	config.vm.provision :shell, inline: $provision

	# Disable default share
	config.vm.synced_folder ".", "/vagrant", disabled: true

	# Our shared directory
	config.vm.synced_folder "..", "/srv/cyphre-client", owner: "vagrant", group: "vagrant", create: true
end
